spring:
  application:
    name: spring-cloud-config

  cloud:
    config:
      enabled: true
      label: master
      server:
        git:
          uri: https://github.com/love-somnus/cloud
          search-paths: config-repository
          username: love-somnus
          password: miss332512
          
server:
  port: 8888

#加入注册中心，实现高可用
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
