spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-config
  
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
        - VM.*
      preferredNetworks:
        - 192.168
    config:
      enabled: true
      label: master
      server:
        git:
          uri: https://github.com/love-somnus/cloud
          search-paths: config-repository
          username: love-somnus
          password: miss332512

  security:
    user:
      name: root
      password: passw0rd     

server:
  port: 8888

#加入注册中心，实现高可用
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
