server:
  port: 8020

spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-zipkin

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}