server:
  port: 8888

spring:
  application:
    name: spring-cloud-discovery
  profiles:
    active: dev   

  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
      preferredNetworks:
        - 192.168
  
  rabbitmq:
    host: 121.43.162.28
    port: 5672
    username: guest
    password: guest
  
  security:
    user:
      name: root
      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
