server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-discovery
  rabbitmq:
    host: cloud-mq-rabbit
    port: 5672
    username: guest
    password: guest

  security:
    user:
      name: root
      password: root